//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Easy_TravelEntities1 : DbContext
    {
        public Easy_TravelEntities1()
            : base("name=Easy_TravelEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accountant> Accountants { get; set; }
        public DbSet<AccountantList> AccountantLists { get; set; }
        public DbSet<AdminList> AdminLists { get; set; }
        public DbSet<BookedHotel> BookedHotels { get; set; }
        public DbSet<BookedVehicle> BookedVehicles { get; set; }
        public DbSet<CusLogin> CusLogins { get; set; }
        public DbSet<HotelBooking> HotelBookings { get; set; }
        public DbSet<HotelReg> HotelRegs { get; set; }
        public DbSet<Inq> Inqs { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<RoomList> RoomLists { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<TransportReg> TransportRegs { get; set; }
        public DbSet<VehicleBooking> VehicleBookings { get; set; }
        public DbSet<TicketBooking> TicketBookings { get; set; }
    }
}
