//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomList
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Place { get; set; }
        public string Type { get; set; }
        public string Price { get; set; }
        public string Offer { get; set; }
        public string ExtraInfo { get; set; }
    }
}
