//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketBooking
    {
        public int CusID { get; set; }
        public string VehicleName { get; set; }
        public string StartingPoint { get; set; }
        public string FinishingPont { get; set; }
        public string VehicleType { get; set; }
        public string BookingDate { get; set; }
        public string SeatNO { get; set; }
        public string Payment { get; set; }
        public string TransactionNO { get; set; }
        public string Status { get; set; }
    }
}
